function Get-CpNetworkDeviceGroups {
  [CmdletBinding()]
  param (
    [Parameter(
      Mandatory = $false,
      HelpMessage = "A ClearPass session generated by New-CpSession.")]
    [Session]$Session=$global:CpSession,

    [Parameter(
      Mandatory = $false,
      HelpMessage = "Maximum number of items to return (1 – 1000).")]
    [Int]$Limit=25,

    [Parameter(
      Mandatory = $false,
      HelpMessage = "Zero based offset to start from.")]
    [Int]$Offset=0,

    [Parameter(
      Mandatory = $false,
      HelpMessage = "Sort ordering for returned items.")]
    [String]$Sort="id",

    [Parameter(
      Mandatory = $false,
      HelpMessage = "Sort ordering for returned items.")]
    [String]$Filter="{}",

    [Parameter(
      Mandatory = $false,
      HelpMessage = "Don't verify the server certificate.")]
    [Switch]$SkipCertificateCheck
  )

  if($Filter -ne "{}"){
    [String]$Filter = [System.Web.HttpUtility]::UrlEncode(($Filter | ConvertTo-Json -Depth 100))
  }

  $uri = [Uri]"https://$($Session.Hostname)/api/network-device-group?filter=$($Filter)&sort=+$($Sort)&offset=$($OffSet)&limit=$($Limit)"

  $headers = @{
    "Authorization" = "Bearer $($Session.AccessToken)"
    "Accept" = "application/json"
  }

  $params = @{
    Uri = $uri.OriginalString
    Method = "Get"
    Headers = $headers
    SkipCertificateCheck = $SkipCertificateCheck
  }

  try{
    $response = Invoke-RestMethod @params

    $response.'_embedded'.items | ForEach-Object {
      $networkDeviceGroup = [NetworkDeviceGroup]@{
        Id              = $_.id
        Name            = $_.name
        Description     = $_.description
        GroupFormat     = $_.group_format
        Value           = $_.value
      }
      
      Write-Output $networkDeviceGroup
    }
  }
  catch {
    Write-Error $_
  }
}